version: "3"

services:

  db:
    image: postgres
    expose:
      - 5432
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Zoro15510990lufy
